<?php
// dev_ops_hub.php - System Ops & Database Hub (Phase 3)
// ศูนย์จัดการความปลอดภัย สำรองข้อมูล และตรวจสอบ Log สำหรับ Developer
require_once __DIR__ . '/env_loader.php';
require_once 'config.php';
require_once 'db.php';
require_once 'security.php';
require_once 'auth.php';
require_once 'logger.php';

// บังคับสิทธิ์ต้องเป็น Developer เท่านั้น
requireRole(['developer']);
$user = currentUser();
$csrf = generate_csrf_token();
$message = '';
$msg_type = '';

// =========================================================
// 1. จัดการ POST Requests (Backup, Clear Logs, Surgery)
// =========================================================

// ตรวจสอบการขอ Backup Database (ต้องทำก่อน Output HTML)
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action']) && $_POST['action'] === 'export_db') {
    if (!isset($_POST['csrf_token']) || !hash_equals($_SESSION['csrf_token'], $_POST['csrf_token'])) {
        die("CSRF Token Verification Failed.");
    }
    
    // เริ่มกระบวนการสร้าง SQL Dump ด้วย PHP
    $tables = [];
    $result = $pdo->query("SHOW TABLES");
    while($row = $result->fetch_row()) {
        $tables[] = $row[0];
    }
    
    $sqlScript = "-- Bankha System Database Backup\n";
    $sqlScript .= "-- Generated by Dev Ops Hub (Phase 3)\n";
    $sqlScript .= "-- Date: " . date('Y-m-d H:i:s') . "\n\n";
    $sqlScript .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
    $sqlScript .= "START TRANSACTION;\n";
    $sqlScript .= "SET time_zone = \"+07:00\";\n\n";

    foreach ($tables as $table) {
        $result = $pdo->query("SHOW CREATE TABLE `$table`");
        $row = $result->fetch_row();
        
        $sqlScript .= "-- --------------------------------------------------------\n";
        $sqlScript .= "-- Table structure for table `$table`\n";
        $sqlScript .= "-- --------------------------------------------------------\n";
        $sqlScript .= "DROP TABLE IF EXISTS `$table`;\n";
        $sqlScript .= $row[1] . ";\n\n";
        
        $result = $pdo->query("SELECT * FROM `$table`");
        $columnCount = $result->field_count;
        $rowCount = $result->rowCount();
        
        if ($rowCount > 0) {
            $sqlScript .= "-- Dumping data for table `$table`\n";
            $sqlScript .= "INSERT INTO `$table` VALUES \n";
            
            $counter = 0;
            while ($row = $result->fetch_row()) {
                $sqlScript .= "(";
                for ($j = 0; $j < $columnCount; $j++) {
                    if (isset($row[$j])) {
                        $escapedString = $pdo->real_escape_string($row[$j]);
                        $sqlScript .= "'" . $escapedString . "'";
                    } else {
                        $sqlScript .= "NULL";
                    }
                    if ($j < ($columnCount - 1)) {
                        $sqlScript .= ", ";
                    }
                }
                $counter++;
                if ($counter < $rowCount) {
                    $sqlScript .= "),\n";
                } else {
                    $sqlScript .= ");\n\n";
                }
            }
        }
    }
    $sqlScript .= "COMMIT;\n";

    $backup_file_name = 'backup_bankha_' . date('Ymd_His') . '.sql';
    
    systemLog($user['id'], 'SYSTEM_BACKUP', "Downloaded full database SQL dump.");
    
    header('Content-Type: application/sql');
    header('Content-Disposition: attachment; filename=' . $backup_file_name);
    echo $sqlScript;
    exit;
}

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!isset($_POST['csrf_token']) || !hash_equals($_SESSION['csrf_token'], $_POST['csrf_token'])) {
        die("CSRF Token Verification Failed.");
    }
    $action = $_POST['action'] ?? '';

    if ($action === 'clear_old_logs') {
        // ลบ Log ที่เก่ากว่า 30 วัน
        $stmt = $pdo->query("DELETE FROM system_logs WHERE created_at < DATE_SUB(NOW(), INTERVAL 30 DAY)");
        if ($stmt) {
            $deleted = $pdo->rowCount();
            $message = "✅ ลบประวัติ Log ที่เก่ากว่า 30 วันสำเร็จ (จำนวน {$deleted} รายการ)";
            $msg_type = "success";
            systemLog($user['id'], 'CLEANUP', "Cleared old system logs ({$deleted} rows)");
        } else {
            $message = "❌ เกิดข้อผิดพลาด: " . $pdo->error;
            $msg_type = "error";
        }
    } elseif ($action === 'run_surgery') {
        // จำลองการรัน Surgery Script (เช่น เช็คตารางซ้ำซ้อนและซ่อมแซม)
        // เพื่อความปลอดภัยของข้อมูลจริง ส่วนนี้จะทำแค่ Check Database Integrity
        $tables_to_check = ['users', 'classes', 'quests', 'chemicals', 'reactions', 'ipst_quest_library'];
        $missing = [];
        foreach($tables_to_check as $tb) {
            $chk = $pdo->query("SHOW TABLES LIKE '{$tb}'");
            if($chk->rowCount() == 0) $missing[] = $tb;
        }
        
        if(count($missing) > 0) {
            $message = "⚠️ พบตารางสูญหาย: " . implode(", ", $missing) . ". กรุณารัน Database Patch!";
            $msg_type = "error";
        } else {
            $message = "✅ Database Integrity Check Passed! โครงสร้างตารางสมบูรณ์ 100%";
            $msg_type = "success";
            systemLog($user['id'], 'DB_SURGERY', "Ran Database Integrity Check: PASS");
        }
    }
}

// =========================================================
// 2. ดึงข้อมูลประกอบหน้าจอ (System Logs & DB Stats)
// =========================================================

// ดึง Logs สูงสุด 500 รายการล่าสุด สำหรับ Terminal
$logs = [];
$res_logs = $pdo->query("
    SELECT sl.*, u.username, u.role 
    FROM system_logs sl 
    LEFT JOIN users u ON sl.user_id = u.id 
    ORDER BY sl.created_at DESC LIMIT 500
");
if ($res_logs) {
    while ($row = $res_logs->fetch()) {
        $logs[] = $row;
    }
}

// ดึงขนาดของตารางในฐานข้อมูลคร่าวๆ (ถ้ามีสิทธิ์ดู information_schema)
$db_stats = [];
$total_size_mb = 0;
$res_size = $pdo->query("
    SELECT table_name AS `Table`, 
    round(((data_length + index_length) / 1024 / 1024), 2) `Size (MB)`,
    table_rows AS `Rows`
    FROM information_schema.TABLES 
    WHERE table_schema = DATABASE()
    ORDER BY (data_length + index_length) DESC
");
if ($res_size) {
    while ($row = $res_size->fetch()) {
        $db_stats[] = $row;
        $total_size_mb += $row['Size (MB)'];
    }
}
?>

<!DOCTYPE html>
<html lang="th">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>System Ops Hub | Developer</title>
    <link href="https://fonts.googleapis.com/css2?family=Prompt:wght@300;400;600;700&family=Orbitron:wght@500;700&family=Share+Tech+Mono&display=swap" rel="stylesheet">
    
    <style>
        :root {
            --bg-dark: #020617;
            --bg-panel: rgba(15, 23, 42, 0.85);
            --border-glass: rgba(148, 163, 184, 0.2);
            --text-main: #f8fafc;
            --text-muted: #94a3b8;
            --neon-blue: #38bdf8;
            --neon-purple: #c084fc;
            --neon-green: #4ade80;
            --neon-red: #f87171;
            --neon-orange: #fb923c;
        }

        body {
            margin: 0; padding: 0; font-family: 'Prompt', sans-serif;
            background-color: var(--bg-dark); color: var(--text-main);
            background-image: 
                radial-gradient(circle at 80% 10%, rgba(74, 222, 128, 0.05), transparent 30%),
                radial-gradient(circle at 20% 90%, rgba(248, 113, 113, 0.05), transparent 30%);
            min-height: 100vh; display: flex; flex-direction: column;
        }

        /* Topbar */
        .topbar {
            height: 70px; background: rgba(2, 6, 23, 0.9); backdrop-filter: blur(10px);
            border-bottom: 1px solid var(--border-glass);
            display: flex; justify-content: space-between; align-items: center; padding: 0 30px;
            position: sticky; top: 0; z-index: 100;
        }
        .topbar h1 { margin: 0; font-family: 'Orbitron', sans-serif; font-size: 1.5rem; color: var(--neon-green); text-shadow: 0 0 10px rgba(74, 222, 128, 0.4); }
        .btn-back { color: var(--text-muted); text-decoration: none; font-weight: bold; border: 1px solid var(--border-glass); padding: 8px 15px; border-radius: 8px; transition: 0.3s; }
        .btn-back:hover { background: rgba(255,255,255,0.1); color: white; }

        .container { max-width: 1400px; margin: 30px auto; padding: 0 20px; flex: 1; width: 100%; box-sizing: border-box; }
        
        .alert-box { padding: 15px 20px; border-radius: 8px; margin-bottom: 20px; font-weight: bold; animation: fadeIn 0.5s; border: 1px solid transparent; }
        .alert-success { background: rgba(74, 222, 128, 0.1); color: var(--neon-green); border-color: rgba(74, 222, 128, 0.3); }
        .alert-error { background: rgba(248, 113, 113, 0.1); color: var(--neon-red); border-color: rgba(248, 113, 113, 0.3); }
        @keyframes fadeIn { from { opacity: 0; transform: translateY(-10px); } to { opacity: 1; transform: translateY(0); } }

        .tabs { display: flex; gap: 10px; margin-bottom: 20px; border-bottom: 2px solid var(--border-glass); padding-bottom: 10px; }
        .tab-btn { background: transparent; color: var(--text-muted); border: none; padding: 10px 25px; font-size: 1.1rem; font-weight: bold; cursor: pointer; border-radius: 10px 10px 0 0; transition: 0.3s; font-family: inherit; position: relative;}
        .tab-btn:hover { color: white; background: rgba(255,255,255,0.05); }
        .tab-btn.active { color: var(--neon-green); background: rgba(74, 222, 128, 0.1); }
        .tab-btn.active::after { content: ''; position: absolute; bottom: -12px; left: 0; width: 100%; height: 2px; background: var(--neon-green); box-shadow: 0 0 10px var(--neon-green); }

        .tab-content { display: none; animation: fadeIn 0.4s; }
        .tab-content.active { display: block; }

        /* ================= TERMINAL STYLES ================= */
        .terminal-wrapper {
            background: #000;
            border: 1px solid #1e293b;
            border-radius: 12px;
            box-shadow: inset 0 0 20px rgba(0,0,0,0.8), 0 10px 30px rgba(0,0,0,0.5);
            display: flex;
            flex-direction: column;
            height: 70vh;
        }

        .terminal-header {
            background: #0f172a;
            padding: 15px 20px;
            border-bottom: 1px solid #1e293b;
            border-radius: 12px 12px 0 0;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .terminal-search input {
            background: rgba(255,255,255,0.05);
            border: 1px solid var(--border-glass);
            color: var(--neon-green);
            padding: 8px 15px;
            border-radius: 6px;
            font-family: 'Share Tech Mono', monospace;
            width: 300px;
            outline: none;
        }
        .terminal-search input:focus { border-color: var(--neon-green); }

        .terminal-body {
            padding: 20px;
            flex: 1;
            overflow-y: auto;
            font-family: 'Share Tech Mono', monospace;
            font-size: 0.95rem;
            line-height: 1.5;
            scrollbar-width: thin;
            scrollbar-color: var(--neon-green) #000;
        }

        .log-line { margin-bottom: 5px; display: flex; gap: 10px; word-break: break-all; border-bottom: 1px solid rgba(255,255,255,0.05); padding-bottom: 5px;}
        .log-line:hover { background: rgba(255,255,255,0.03); }
        .t-time { color: #64748b; white-space: nowrap;}
        .t-ip { color: #475569; white-space: nowrap; width: 120px;}
        .t-user { color: var(--neon-purple); white-space: nowrap; width: 150px; font-weight: bold;}
        .t-action { color: var(--neon-blue); white-space: nowrap; width: 160px; font-weight: bold;}
        .t-detail { color: var(--text-main); flex: 1;}
        .t-detail.error { color: var(--neon-red); }
        .t-detail.success { color: var(--neon-green); }

        /* ================= DB SURGERY STYLES ================= */
        .ops-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(350px, 1fr));
            gap: 25px;
        }

        .ops-card {
            background: var(--bg-panel);
            border: 1px solid var(--border-glass);
            border-radius: 16px;
            padding: 30px;
            transition: 0.3s;
            display: flex;
            flex-direction: column;
            box-shadow: 0 10px 30px rgba(0,0,0,0.2);
        }

        .ops-card:hover {
            border-color: rgba(255,255,255,0.2);
            transform: translateY(-5px);
        }

        .ops-icon {
            font-size: 3rem;
            margin-bottom: 15px;
        }

        .ops-card h3 {
            margin: 0 0 10px 0;
            font-size: 1.4rem;
            color: var(--text-main);
        }

        .ops-card p {
            color: var(--text-muted);
            line-height: 1.6;
            margin: 0 0 20px 0;
            flex: 1;
        }

        .btn-execute {
            width: 100%;
            padding: 15px;
            border: none;
            border-radius: 10px;
            font-family: inherit;
            font-weight: bold;
            font-size: 1.1rem;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 10px;
            transition: 0.3s;
        }

        .btn-backup { background: linear-gradient(135deg, #10b981, #059669); color: white; box-shadow: 0 5px 15px rgba(16, 185, 129, 0.3); }
        .btn-backup:hover { background: #059669; transform: scale(1.02); box-shadow: 0 8px 20px rgba(16, 185, 129, 0.5); }

        .btn-clean { background: linear-gradient(135deg, #f59e0b, #d97706); color: white; box-shadow: 0 5px 15px rgba(245, 158, 11, 0.3); }
        .btn-clean:hover { background: #d97706; transform: scale(1.02); }

        .btn-surgery { background: linear-gradient(135deg, #ef4444, #b91c1c); color: white; box-shadow: 0 5px 15px rgba(239, 68, 68, 0.3); }
        .btn-surgery:hover { background: #b91c1c; transform: scale(1.02); box-shadow: 0 8px 20px rgba(239, 68, 68, 0.5); }

        /* DB Stats Table */
        .db-stats-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
            background: #0f172a;
            border-radius: 10px;
            overflow: hidden;
            border: 1px solid var(--border-glass);
        }
        .db-stats-table th { background: rgba(255,255,255,0.05); padding: 12px 15px; text-align: left; color: var(--text-muted); border-bottom: 1px solid var(--border-glass);}
        .db-stats-table td { padding: 12px 15px; border-bottom: 1px solid rgba(255,255,255,0.02); font-family: 'Share Tech Mono';}
        
    </style>
</head>
<body>

    <header class="topbar">
        <h1>🛡️ System Ops & Database Hub</h1>
        <a href="dashboard_dev.php" class="btn-back">⬅ Back to Dashboard</a>
    </header>

    <div class="container">
        <?php if ($message): ?>
            <div class="alert-box alert-<?= $msg_type ?>">
                <?= $message ?>
            </div>
        <?php endif; ?>

        <div class="tabs">
            <button class="tab-btn active" onclick="switchTab('tab-terminal', this)">💻 Live System Logs (Terminal)</button>
            <button class="tab-btn" onclick="switchTab('tab-ops', this)">💽 Database Operations</button>
        </div>

        <div id="tab-terminal" class="tab-content active">
            <div class="terminal-wrapper">
                <div class="terminal-header">
                    <div style="font-family:'Share Tech Mono'; color:var(--text-muted);">
                        <span style="color:var(--neon-green);">root@bankha-server</span>:~/var/log/system$ tail -f auth.log
                    </div>
                    <div class="terminal-search">
                        <input type="text" id="logSearch" placeholder="Filter logs (e.g., username, ERROR)..." onkeyup="filterLogs()">
                    </div>
                </div>
                <div class="terminal-body" id="terminalBody">
                    <?php if (count($logs) > 0): ?>
                        <?php foreach ($logs as $log): ?>
                            <?php 
                                $isFail = strpos(strtoupper($log['action']), 'FAIL') !== false || strpos(strtoupper($log['action']), 'ERROR') !== false;
                                $isSuccess = strpos(strtoupper($log['action']), 'SUCCESS') !== false;
                                $detailClass = $isFail ? 'error' : ($isSuccess ? 'success' : '');
                                $userDisplay = $log['username'] ? $log['username'] . " [{$log['role']}]" : 'SYSTEM/GUEST';
                                $ip = $log['ip_address'] ? $log['ip_address'] : 'UNKNOWN';
                            ?>
                            <div class="log-line">
                                <span class="t-time">[<?= htmlspecialchars($log['created_at']) ?>]</span>
                                <span class="t-ip"><?= htmlspecialchars($ip) ?></span>
                                <span class="t-user"><?= htmlspecialchars($userDisplay) ?></span>
                                <span class="t-action"><?= htmlspecialchars($log['action']) ?></span>
                                <span class="t-detail <?= $detailClass ?>">=> <?= htmlspecialchars($log['details']) ?></span>
                            </div>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <div class="log-line" style="color: var(--text-muted);">No system logs found.</div>
                    <?php endif; ?>
                    <div class="log-line" style="margin-top: 10px;">
                        <span style="animation: blink 1s infinite; color:var(--neon-green);">_</span>
                    </div>
                </div>
            </div>
            <style>@keyframes blink { 0%, 100% { opacity: 1; } 50% { opacity: 0; } }</style>
        </div>

        <div id="tab-ops" class="tab-content">
            <div class="ops-grid">
                
                <div class="ops-card" style="border-top: 4px solid var(--neon-green);">
                    <div class="ops-icon">💾</div>
                    <h3 style="color: var(--neon-green);">One-Click Backup (.sql)</h3>
                    <p>ดาวน์โหลดฐานข้อมูล <code>classroom_mgmt</code> ทั้งหมด (โครงสร้างตารางและข้อมูล) ออกมาเป็นไฟล์ SQL เพื่อสำรองข้อมูล ป้องกันความผิดพลาดก่อนอัปเดตระบบ</p>
                    <form method="POST" style="margin:0;">
                        <input type="hidden" name="csrf_token" value="<?= $csrf ?>">
                        <input type="hidden" name="action" value="export_db">
                        <button type="submit" class="btn-execute btn-backup">
                            ⬇️ Download Database Backup
                        </button>
                    </form>
                </div>

                <div class="ops-card" style="border-top: 4px solid var(--neon-orange);">
                    <div class="ops-icon">🧹</div>
                    <h3 style="color: var(--neon-orange);">System Log Cleanup</h3>
                    <p>เคลียร์ข้อมูลประวัติการใช้งาน (System Logs) ที่เก่ากว่า 30 วัน เพื่อลดขนาดฐานข้อมูลและทำให้ Query ทำงานได้รวดเร็วขึ้น</p>
                    <form method="POST" style="margin:0;" onsubmit="return confirm('ยืนยันการลบประวัติ Log ที่เก่ากว่า 30 วันทิ้งทั้งหมด? (ไม่สามารถกู้คืนได้)');">
                        <input type="hidden" name="csrf_token" value="<?= $csrf ?>">
                        <input type="hidden" name="action" value="clear_old_logs">
                        <button type="submit" class="btn-execute btn-clean">
                            🗑️ Clear Old Logs (>30 Days)
                        </button>
                    </form>
                </div>

                <div class="ops-card" style="border-top: 4px solid var(--neon-red);">
                    <div class="ops-icon">🛠️</div>
                    <h3 style="color: var(--neon-red);">Database Surgery / Integrity</h3>
                    <p>ตรวจสอบความสมบูรณ์ของโครงสร้างฐานข้อมูล (Integrity Check) ว่ามีตารางหลักๆ ครบถ้วนตาม Phase 3 หรือไม่</p>
                    <form method="POST" style="margin:0;">
                        <input type="hidden" name="csrf_token" value="<?= $csrf ?>">
                        <input type="hidden" name="action" value="run_surgery">
                        <button type="submit" class="btn-execute btn-surgery">
                            ⚡ Run Integrity Check
                        </button>
                    </form>
                </div>

                <div class="ops-card" style="grid-column: 1 / -1; border-top: 4px solid var(--neon-blue);">
                    <h3 style="color: var(--neon-blue); margin-bottom: 5px;">📊 Database Storage Statistics</h3>
                    <p style="margin-bottom: 10px;">Total Size: <strong style="color:white;"><?= number_format($total_size_mb, 2) ?> MB</strong></p>
                    
                    <div style="overflow-x: auto;">
                        <table class="db-stats-table">
                            <thead>
                                <tr>
                                    <th>Table Name</th>
                                    <th>Estimated Rows</th>
                                    <th>Approx. Size (MB)</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php if(empty($db_stats)): ?>
                                    <tr><td colspan="3" style="text-align:center; color:var(--text-muted);">Permission Denied to read information_schema</td></tr>
                                <?php else: ?>
                                    <?php foreach($db_stats as $stat): ?>
                                    <tr>
                                        <td style="color:var(--neon-blue);"><?= htmlspecialchars($stat['Table']) ?></td>
                                        <td><?= number_format($stat['Rows']) ?></td>
                                        <td><?= number_format($stat['Size (MB)'], 2) ?></td>
                                    </tr>
                                    <?php endforeach; ?>
                                <?php endif; 
    } catch (\PDOException $e) {
        error_log('[db_error] ' . $e->getMessage() . ' in ' . __FILE__ . ':' . __LINE__);
        if (!headers_sent()) {
            http_response_code(500);
        }
        $is_dev = defined('APP_ENV') && APP_ENV === 'development' && defined('APP_DEBUG') && APP_DEBUG;
        $msg = $is_dev ? htmlspecialchars($e->getMessage(), ENT_QUOTES, 'UTF-8') : 'กรุณาลองใหม่อีกครั้ง';
        die('<div style="font-family:sans-serif;text-align:center;padding:3rem">'
          . '<h3 style="color:#ef4444">เกิดข้อผิดพลาดในระบบฐานข้อมูล</h3>'
          . '<p style="color:#6b7280">' . $msg . '</p>'
          . '<a href="index.php" style="color:#3b82f6">← กลับหน้าหลัก</a>'
          . '</div>');
    }

?>

try {
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>

    </div>

    <script>
        // ระบบสลับหน้า Tab
        function switchTab(tabId, btn) {
            document.querySelectorAll('.tab-content').forEach(el => el.classList.remove('active'));
            document.querySelectorAll('.tab-btn').forEach(el => el.classList.remove('active'));
            document.getElementById(tabId).classList.add('active');
            btn.classList.add('active');
            
            // เลื่อน Terminal ลงล่างสุดเมื่อเปิด Tab
            if(tabId === 'tab-terminal') {
                const term = document.getElementById('terminalBody');
                term.scrollTop = term.scrollHeight;
            }
        }

        // ระบบค้นหาใน Terminal (Live Filter)
        function filterLogs() {
            const query = document.getElementById('logSearch').value.toLowerCase();
            const lines = document.querySelectorAll('.log-line');
            lines.forEach(line => {
                if (line.innerText.toLowerCase().includes(query)) {
                    line.style.display = 'flex';
                } else {
                    line.style.display = 'none';
                }
            });
        }

        // เลื่อน Terminal ลงล่างสุดอัตโนมัติเมื่อโหลดหน้าเว็บครั้งแรก
        window.onload = function() {
            const term = document.getElementById('terminalBody');
            term.scrollTop = term.scrollHeight;
        };
    </script>
</body>
</html>